// <auto-generated />
namespace ThuVien.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class update_issue : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_issue));
        
        string IMigrationMetadata.Id
        {
            get { return "202306270835491_update_issue"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
