// <auto-generated />
namespace ThuVien.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class drop_cl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(drop_cl));
        
        string IMigrationMetadata.Id
        {
            get { return "202306281807236_drop_cl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
